name: auto-code-rover
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.2
  - setuptools=68.2.2
  - python=3.12.5 # Move Python here instead of under pip
  - pip
  - pip:
      - -r requirements-dev.txt
      # - unidiff
      # - annotated-types==0.6.0
      # - anyio==4.2.0
      # - beautifulsoup4==4.12.3
      # - certifi==2023.11.17
      # - distro==1.9.0
      # - docstring-parser==0.15
      # - h11==0.14.0
      # - httpcore==1.0.2
      # - httpx==0.26.0
      # - idna==3.6
      # - lxml==5.1.0
      # - openai==1.8.0
      # - pydantic==2.7.1
      # - pydantic-core==2.18.2
      # - python-dotenv==1.0.0
      # - sniffio==1.3.0
      # - soupsieve==2.5
      # - tenacity==8.2.3
      # - termcolor==2.4.0
      # - tqdm==4.66.1
      # - typing-extensions==4.9.0
      # - unittest-xml-reporting==3.2.0
      # - coverage
      # - pylint
